const products= [
    {
        id:"101",
        name:"abcd product",
        brand:"pedigree",
        pets:["dog","cat"],
        category:"food",
        base_price:100.00,
        base_currency:"AED",
        in_stock:false,
        likes:5,
        featured_product:true,
        offer_status:false,
        offer_price:null,
        description:"All things about this product ",
        thumbnail:"/images/brands/pedigree-2.jpg",
        related_images:["Image_1_location","Image_2_location"],
        main_uom:"Packet",
        main_qty:1,
        sub_uom:"kg",
        sub_qty:5,
    },
    {
        id:"102",
        name:"efgh product",
        brand:"royal-cannin",
        pets:["dog"],
        category:"food",
        base_price:100.00,
        base_currency:"AED",
        in_stock:true,
        likes:5,
        featured_product:true,
        offer_status:false,
        offer_price:null,
        description:"All things about this product ",
        thumbnail:"/images/brands/pedigree-2.jpg",
        related_images:["Image_1_location","Image_2_location"],
        main_uom:"Packet",
        main_qty:1,
        sub_uom:"kg",
        sub_qty:5,
    },
    {
        id:"103",
        name:"fghi product",
        brand:"whiskas",
        pets:["dog"],
        category:"food",
        base_price:100.00,
        base_currency:"AED",
        in_stock:true,
        likes:5,
        featured_product:true,
        offer_status:false,
        offer_price:null,
        description:"All things about this product ",
        thumbnail:"/images/brands/pedigree-2.jpg",
        related_images:["Image_1_location","Image_2_location"],
        main_uom:"Packet",
        main_qty:1,
        sub_uom:"kg",
        sub_qty:5,
    },
    {
        id:"104",
        name:"jklmn product",
        brand:"pedigree",
        pets:["fish"],
        category:"food",
        base_price:100.00,
        base_currency:"AED",
        in_stock:true,
        likes:5,
        featured_product:true,
        offer_status:false,
        offer_price:null,
        description:"All things about this product ",
        thumbnail:"/images/brands/pedigree-2.jpg",
        related_images:["Image_1_location","Image_2_location"],
        main_uom:"Packet",
        main_qty:1,
        sub_uom:"kg",
        sub_qty:5,
    },
    {
        id:"105",
        name:"jklmn product",
        brand:"royal-cannin",
        pets:["bird"],
        category:"food",
        base_price:100.00,
        base_currency:"AED",
        in_stock:true,
        likes:5,
        featured_product:true,
        offer_status:false,
        offer_price:null,
        description:"All things about this product ",
        thumbnail:"/images/brands/pedigree-2.jpg",
        related_images:["Image_1_location","Image_2_location"],
        main_uom:"Packet",
        main_qty:1,
        sub_uom:"kg",
        sub_qty:5,
    },
    {   id:"106",
        name:"jklmn product",
        brand:"royal-cannin",
        pets:["bird"],
        category:"cage",
        base_price:100.00,
        base_currency:"AED",
        in_stock:true,
        likes:5,
        featured_product:true,
        offer_status:false,
        offer_price:null,
        description:"All things about this product ",
        thumbnail:"/images/brands/pedigree-2.jpg",
        related_images:["Image_1_location","Image_2_location"],
        main_uom:"Packet",
        main_qty:1,
        sub_uom:"kg",
        sub_qty:5,
    },
    {
        id:"107",
        name:"qpsk product",
        brand:"whiskas",
        pets:["cat"],
        category:"toys",
        base_price:100.00,
        base_currency:"AED",
        in_stock:true,
        likes:5,
        featured_product:true,
        offer_status:false,
        offer_price:null,
        description:"All things about this product ",
        thumbnail:"/images/brands/pedigree-2.jpg",
        related_images:["Image_1_location","Image_2_location"],
        main_uom:"Packet",
        main_qty:1,
        sub_uom:"kg",
        sub_qty:5,
    }
]

module.exports = products;